// examples/vue/src/App.vue
<script setup lang="ts">
import * as SkillIcons from '@skill-icons/vue';

// Get all icon components
const iconEntries = Object.entries(SkillIcons);
</script>

<template>
  <div class="app-container">
    <h1 class="title">Skill Icons Library</h1>
    <p class="subtitle">Total {{ iconEntries.length }} Icons</p>
    <div class="icons-grid">
      <div v-for="[iconName, IconComponent] in iconEntries" :key="iconName" class="icon-card">
        <div class="icon-container">
          <component :is="IconComponent" />
        </div>
        <span class="icon-name">
          {{ iconName }}
        </span>
      </div>
    </div>
  </div>
</template>

// examples/react/src/App.tsx
import * as SkillIcons from '@skill-icons/react';

function App() {
  // Get all icon components
  const iconEntries = Object.entries(SkillIcons);

  return (
    <div className="app-container">
      <h1 className="title">Skill Icons Library</h1>
      <p className="subtitle">Total {iconEntries.length} Icons</p>
      <div className="icons-grid">
        {iconEntries.map(([iconName, IconComponent]) => (
          <div key={iconName} className="icon-card">
            <div className="icon-container">
              <IconComponent />
            </div>
            <span className="icon-name">{iconName}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

export default App;
